# Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np , random

arr = np.random.randint(1,21,size=(5,5))

arr[:,2]=1

print(arr)

[[ 2 20  1  2  4]
 [ 6 13  1  8  1]
 [10 17  1 14  2]
 [12 15  1 14  5]
 [19 20  1 16  9]]


In [ ]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.