## Numpy

Numpy is a fundamental library for scientific computing in Python.
It provides support for arrays and matrices and along with a collection of mathematical functions to operate on these data structures.

In [3]:
## Installing NUMPY

!pip install numpy

In [7]:
import numpy as np      ## np is an alias for numpy

## Create Arrays using Numpy

#------------------------------------------------------------

# Create an 1D array
arr1 = np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 2D array = 2 square brackets

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array - nested list way

arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
# 2D ARRAY
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


### Create Arrays with some of the In-Built Functions

#### ARANGE fucntion : -

In [16]:

arr1 = np.arange(0,10,2)

arr2 = np.arange(0,10,2).reshape(5,1)

arr3 = np.arange(0,10,1)

print(arr1)

print(arr2)

print(arr3)


[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[0 1 2 3 4 5 6 7 8 9]


#### ONE function : - 


In [17]:
np.ones ((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## Example
arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n",arr)

print("Shape : ",arr.shape)
print(f"Number of dimensions : {arr.ndim}")
print(f"Size(number of elements): {arr.size} ")
print(f"Data type : {arr.dtype}")
print(f"Item size (in bytes) : {arr.itemsize}")

Array: 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of dimensions : 2
Size(number of elements): 6 
Data type : int32
Item size (in bytes) : 4


In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[[1,2,3,4]]])

shape1 = arr1.shape
shape2 = arr2.shape

print(shape1)
print(shape2 )

(5,)
(1, 1, 4)
