## Numpy

Numpy is a fundamental library for scientific computing in Python.
It provides support for arrays and matrices and along with a collection of mathematical functions to operate on these data structures.

In [3]:
## Installing NUMPY

!pip install numpy

In [7]:
import numpy as np      ## np is an alias for numpy

## Create Arrays using Numpy

#------------------------------------------------------------

# Create an 1D array
arr1 = np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 2D array = 2 square brackets

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array - nested list way

arr2 = np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
# 2D ARRAY
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


### Create Arrays with some of the In-Built Functions

#### ARANGE fucntion : -

In [16]:

arr1 = np.arange(0,10,2)

arr2 = np.arange(0,10,2).reshape(5,1)

arr3 = np.arange(0,10,1)

print(arr1)

print(arr2)

print(arr3)


[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[0 1 2 3 4 5 6 7 8 9]


#### ONE function : - 


In [17]:
np.ones ((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Attributes of NumPy

In [ ]:
## Example

arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n",arr)

print("Shape : ",arr.shape)
print(f"Number of dimensions : {arr.ndim}")
print(f"Size(number of elements): {arr.size} ")
print(f"Data type : {arr.dtype}")
print(f"Item size (in bytes) : {arr.itemsize}")

Array: 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of dimensions : 2
Size(number of elements): 6 
Data type : int32
Item size (in bytes) : 4


### Vectorized Operations

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## ELEMENT WISE ADDITION
print(f"Addition : {arr1+arr2}")

## ELEMENT WISE SUBSTRACTION
print(f"substraction : {arr1-arr2}")

## ELEMENT WISE MULTIPLICATION
print(f" product : {arr1*arr2}")

## ELEMENT WISE DIVISION
print(f" division : {arr1/arr2}")

Addition : [11 22 33 44 55]
substraction : [ -9 -18 -27 -36 -45]
 product : [ 10  40  90 160 250]
 division : [0.1 0.1 0.1 0.1 0.1]


### UNIVERSAL FUNCTIONS 
It applie on whole arrays

In [ ]:


arr = np.array([2,3,4,5,6])

## square root
print(f"sqrt : {np.sqrt(arr)}")


## Exponential
print(f" exp : {np.exp(arr)}")

## Sine , Cos , tan
print(f" sin  : {np.sin(arr)}")
print(f" cos : {np.cos(arr)}")
print(f" tan : {np.tan(arr)}")


## natural log
print(f" natural log : {np.log(arr)}")






sqrt : [1.41421356 1.73205081 2.         2.23606798 2.44948974]
 exp : [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
 sin  : [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
 cos : [-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
 tan : [-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
 natural log : [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### ARRAY SLICING AND INDEXING


In [34]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array : \n",arr)

print("\n")
## ------------------------------------
print(f"DIAGONAL ELEMENTS\n")
print(f"First element : {arr[0][0]}") 
print(f"First element : {arr[1][1]}")
print(f"First element : {arr[2][2]}")

# -----------------------------------------------------
## acess elements -> 7,8,11,12
print("\n")

print(f"Get Elements 7,8,11,12")
print(f" {arr[1:, 2:]}")


print("\n")
print(f"Get Elements 3,4,5,6,7,8")
print(f"{arr[0:2,2:]}")

print("\n")
print(f"Get Elements 6,7,10,11")
print(f"{arr[1: , 1:3]}")




array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


DIAGONAL ELEMENTS

First element : 1
First element : 6
First element : 11


Get Elements 7,8,11,12
 [[ 7  8]
 [11 12]]


Get Elements 3,4,5,6,7,8
[[3 4]
 [7 8]]


Get Elements 6,7,10,11
[[ 6  7]
 [10 11]]


MODIFY ARRAYS

In [ ]:
arr[0,0] = 100
print(arr)

print("\n")

arr[1:] = 100
print(arr)


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Practical Applications Using Arrays


In [42]:
## STATISTICAL CONCEPT -- Normalization

data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print(f"Mean : {mean}")


# Median
mean = np.median(data)
print(f"Median: {mean}")


# Standard Deviation
mean = np.std(data)
print(f"Standard Deviation: {mean}")


# Variance
mean = np.var(data)
print(f"Variance: {mean}")

# # Mean
# mean = np.mean(data)
# print(f"Mean : {mean}")


# # Mean
# mean = np.mean(data)
# print(f"Mean : {mean}")









Mean : 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical Operations 

data = np.array(([1,2,3,4,5,6,7,8,9,10]))

print(data[(data>=5) & (data<8)])

print(data[(data>=5) | (data<8)])


data[(data>=5) & (data<8)]



[5 6 7]
[ 1  2  3  4  5  6  7  8  9 10]
