STRUCTURED NUMERICAL STORAGE


In [6]:
## SHAPE + DIMENSION

import numpy as np

arr = np.array([1,2,3,4])

print(arr.shape)

print(arr.ndim)

print(arr.size)

(4,)
1
4


In [7]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)
print(arr.size)

(2, 3)
6


In [13]:
arr = np.array([
    [[1,2,3]]
])

print(f"shape : {arr.shape}")

shape : (1, 1, 3)


In [14]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr.shape

(3, 3)

In [20]:
## Arange Function

arr = np.arange(0,20,4)
print(f"{arr} \n {arr.shape}")

[ 0  4  8 12 16] 
 (5,)


In [21]:
arr = np.ones((3,4))
print(f"{arr}\n{arr.shape}\n{arr.size}")

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
12


In [26]:
arr = np.zeros((2,5))
print(arr)

new_arr = arr.reshape(5,2)

print(new_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [28]:
arr = np.eye(4,3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
np.arange(0,1,0.2)
# arange() creates numbers using a fixed step size.
# “jump by 0.2”

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
np.linspace(0,1,6)
# linspace() creates evenly spaced numbers between two values.
# Gives 6 evenly spaced values from 0 to 1:

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

# Operations + Slicing + Filtering

In [50]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(f"{arr[1:3,1:3]}")
print(f"{arr[1][1]}")
print(f"{arr[2][2]}")
print(f"{arr[0:3,1:2]}")
print(f"{arr[0:2,1:2]}")
arr[0][0] = 30
print(arr)

[[5 6]
 [8 9]]
5
9
[[2]
 [5]
 [8]]
[[2]
 [5]]
[[30  2  3]
 [ 4  5  6]
 [ 7  8  9]]
