In [20]:
# Create an array from 0 to 24 with step 2, reshape into (3,4), multiply by 10, slice and print only [[80,100],[160,180]], then filter and print values greater than 150.


import numpy as np

arr = np.arange(0,24,2)

#reshaping into (3,4)
new_arr = arr.reshape(3,4)

#multiplying with 10
new_arr = (new_arr)*10


print(f"New_Arr : \n {new_arr} \n Sliced : \n{new_arr[1:,0:2]} \n Filtered : \n{new_arr[(new_arr>150)]}")


New_Arr : 
 [[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]] 
 Sliced : 
[[ 80 100]
 [160 180]] 
 Filtered : 
[160 180 200 220]


### Why does NumPy filtering first create a True/False array before returning actual filtered values?

* This is a two step process makes filtering fast and Vectorized
* Vectorized (NumPy uses optimized low-level code internally to make operations fatser and it gets applied to entire array at once instead of using loops)
* NumPy first checks condition on every element individually and it creates a Boolean mask(T/F) array showing which conditions specified condition

* Then during filtering :
* arr[condition]
* NumPy uses:
* True : keeps value
* False : discards value

*And then it returns the resultant array with only True values.

In [ ]:
# Create an array from 1 to 18 with step 3, reshape into (2,3), add 5 to all elements, slice and print only the last two columns, then filter values between 10 and 20.

arr = np.arange(1,18,3)

#Reshaping
arr1 = arr.reshape(2,3)

#Adding 5 to all elements
arr1 = arr1 + 5

print(f"arr1 : \n{arr1}")

#Slice only last two columns 
print(f"Slice : \n{arr1[0:,1:]}")

#Filtering
print(f"Filtering : \n{arr1[(arr1>=10  ) & (arr1 <= 20)]}")


arr1 : 
[[ 6  9 12]
 [15 18 21]]
Slice : 
[[ 9 12]
 [18 21]]
Filtering : 
[12 15 18]


### Why does arr + 5 work on the whole array without using a loop?

NumPy uses vectorization
* Vectorization - uses low level optimized code which gets applied to an entire array at once instead of looping manually through each elements , making it faster and cleaner


In [38]:
# Create a 3×3 array of ones, multiply it by 5, add an identity matrix using eye(), then apply np.sqrt() to the result and print it.

arr = np.ones((3,3))  

#Multiply arr by 5
arr = arr*5

arr1 = np.eye(3,2)
#Adding an identity matrix an arr
arr = arr + np.eye(3) ## 3x3 identity matrix

#operations
result = np.sqrt(arr)


print(f"arr : \n{arr}")
print(f"result : \n{result}")



arr : 
[[6. 5. 5.]
 [5. 6. 5.]
 [5. 5. 6.]]
result : 
[[2.44948974 2.23606798 2.23606798]
 [2.23606798 2.44948974 2.23606798]
 [2.23606798 2.23606798 2.44948974]]


### Why are functions like sqrt, log, sin, and exp called universal functions (ufuncs) in NumPy?

* Functions like sqrt
log
sin
exp
are called universal functions (ufuncs) because they automatically apply the operation element-wise to the entire NumPy array without using manual loops.

They work efficiently on arrays using vectorization and optimized internal implementation.