### ARRAYS + SHAPE + RESHAPE

ATTRIBUTES OF NUMPY
* Shape - array.shape
* Number of dimensions - array.ndim
* Size - arr.size 
* data type - arr.dtype
* item size - arr.itemsize 

NUMBER OF DIMENSIONS (.ndim)
tells how many levels of nesting the array has
[1,2,3] -> 1D -> ndim = 1
[[1,2,3],[3,4,5]] -> ndim = 2

SHAPE (.shape)
Structure of the array.
Each number = size in that dimension
(2,3) - 2 rows , 3 columns

SIZE (.size)
Total number of elements in the array
count everything 
(2,3) - size = 6

ITEMSIZE 
Memory (in bytes) used by one element of the array. Depends on data type
int64 - 8 bytes

nbytes
Total memory used by the array = size × itemsize
6 elements × 8 bytes = 48 bytes


In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n",arr)

print("Shape : ",arr.shape)
print(f"Number of dimensions : {arr.ndim}")
print(f"Size(number of elements): {arr.size} ")
print(f"Data type : {arr.dtype}")
print(f"Item size (in bytes) : {arr.itemsize}")

Array: 
 [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
Number of dimensions : 2
Size(number of elements): 6 
Data type : int32
Item size (in bytes) : 4


In [3]:
# Q1 — Basic array + shape

# Create a NumPy array:

# [10, 20, 30, 40, 50]

# Print:
# the array
# its shape
# its type

import numpy as np

arr1 = np.array([10,20,30,40,50])
print(f"{arr1} \nShape : {arr1.shape} \nType : {type(arr1)}")

[10 20 30 40 50] 
Shape : (5,) 
Type : <class 'numpy.ndarray'>


In [5]:
# Q2 — 2D array understanding

# Create this array:

# [[1,2,3],
#  [4,5,6]]

# Print:

# array
# shape
# number of dimensions (ndim)

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(f"{arr} \n Shape : {arr.shape} \n ndim : {arr.ndim}")


[[1 2 3]
 [4 5 6]] 
 Shape : (2, 3) 
 ndim : 2


In [16]:
# Q3 — Reshape (important)

# Create:

# [1,2,3,4,5,6]

# Convert it into:

# shape (2,3)
# shape (3,2)

# Print both results

arr = np.array([1,2,3,4,5,6])
print(f"{arr} \n shape : {arr.shape}")

arr1 = arr.reshape(2,3)
print("arr1 : ",arr1)
print("\n")
arr2 = arr.reshape(3,2)
print("arr2 :",arr2)




[1 2 3 4 5 6] 
 shape : (6,)
arr1 :  [[1 2 3]
 [4 5 6]]


arr2 : [[1 2]
 [3 4]
 [5 6]]


In [17]:
# Q4 — Trap question (tests real understanding)

arr = np.array([1,2,3,4,5])
arr.reshape(2,3)

print(arr)

ValueError: cannot reshape array of size 5 into shape (2,3)

So, you cannot reshape because data is not enough to fill the structure 

CORE RULE : Total elements must remain constant in reshaping

