In [ ]:

# Write code to:

# create an array from 0 to 15 with step 3
# print:
# shape
# ndim
# size

import numpy as np

arr = np.arange(0,15,3)

print(f"{arr} \n Shape : {arr.shape} \n Dim : {arr.ndim} \n Size : {arr.size}")

[ 0  3  6  9 12] 
 Shape : (5,) 
 Dim : 1 
 Size : 5


### Why Does Shape (5,) does not means 1 rows and 5 columns?

* Because an array with shape (5,) means it is a 1D array with 5 elements , not 1 rows and 5 columns 
* Because 1 rows and 5 columns would be this (1,5) which is a 2D array.

In [13]:
# Write code to:

# create a 3×3 array of zeros
# reshape it into (1,9)
# print:
# original shape
# reshaped shape

arr = np.zeros((3,3))

print(f"OG : \n{arr}")

arr1 = arr.reshape((1,9))

print(f"Reshaped : {arr1}")

arr2 = arr.reshape((9,1))

print(f"Reshaped : {arr2}")


OG : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Reshaped : [[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Reshaped : [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Why is this valid? (2,6) for an array with 12 elements, but this is invalid? (3,5)

* (2,6) is valid for reshaping an array with 12 elements because 2X6 = 12
* (3,5) becomes invalid because 3X5 = 15 , which exceeds the toal array elements .

RESHAPING ONLY WORKS IF : 
rows X columns = Total number of elements in an array 

In [19]:
# Print ONLY:
# [[7,8],
#  [11,12]]

arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]

])



print(arr[1:,2:])

[[ 7  8]
 [11 12]]


### Explain this: arr[1:, 2:] 
* 1 :  rows from index 1 til end
* 2 : columns from index 1 til end 


In [ ]:
# Print:

# values greater than 5
# values between 3 and 8

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[(arr>5)]) 

print(arr[(arr<3)])

print(arr[(arr>3) & (arr<8)])

print(arr[(arr>3) | (arr<8)])



[ 6  7  8  9 10]
[1 2]
[4 5 6 7]
[ 1  2  3  4  5  6  7  8  9 10]


Why does this:  arr > 5  NOT directly return filtered values,but instead returns:True / False

* arr>5 comparison command - returns boolean output
* arr[arr>5]  actual filtering command returns values/elements that are True

* arr>5 is just a simple comparison operation , numpy compares each element individually and returns a Boolean array , showing which positin satisfy the condition, whereas (arr[arr>5]) is actual filtering command and returns only those values which satisfy/.