In [ ]:
# Write code to:

# create 8 evenly spaced values between 0 and 1
# print the array
# print its shape

import numpy as np 

arr = np.linspace(0,1,8)

print(f"Array : {arr}")

print(f"Sahpe : {arr.shape}")

Array : [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]
Sahpe : (8,)


### Why is linspace() preferred over arange() in many mathematical/graphing situations

*linspace() gurantees an exact number of evenly spaced values , which is important in graphs,plotting and simulations and mathematical computations.

*while , arange() is step-based it skips values so floating-point precision can make results inconsistent sometimes

In [10]:
# Write code to:

# create values from 1 to 19 with step 3
# reshape into (2,3)
# square every element using a universal function
# print only last two columns
# filter values greater than 100

arr = np.arange(1,19,3)
print(f"Arr : \n{arr}")

#Reshaping
new_arr = arr.reshape(2,3)
print(f"New Array : \n{new_arr}")

#Square
new_arr = np.square(new_arr)
print(f"Square : \n{new_arr}")

#Last Two Columns

print(f"Last two columns : \n{new_arr[0: , 1: ]}")

#Filter values greater than 10
print(f"Values greater than 10 : \n{new_arr[new_arr>10]}")



Arr : 
[ 1  4  7 10 13 16]
New Array : 
[[ 1  4  7]
 [10 13 16]]
Square : 
[[  1  16  49]
 [100 169 256]]
Last two columns : 
[[ 16  49]
 [169 256]]
Values greater than 10 : 
[ 16  49 100 169 256]


### Why is np.sqrt() called a universal function?

* Because it applies the operation to entire NumPy array using vectorized operations

In [16]:
# Write code to:

# create a 4×4 identity matrix
# multiply entire matrix by 10
# replace all diagonal values with 99
# print only the first 2 rows

arr = np.eye(4)
print(f"array : \n{arr}")

#multiplying
arr = arr*10
print(arr)


arr[0][0] = 99

arr[1][1] = 99

arr[2][2] = 99

arr[3][3] = 99

print(arr)

print(f"New array : \n{arr[ :2]}")


array : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]
[[99.  0.  0.  0.]
 [ 0. 99.  0.  0.]
 [ 0.  0. 99.  0.]
 [ 0.  0.  0. 99.]]
New array : 
[[99.  0.  0.  0.]
 [ 0. 99.  0.  0.]]


### Why is an identity matrix important mathematically?

* Because multiplying any matrix by an identity matrix keeps the original matrix unchanged.


In [22]:
# Create an array from 1 to 15, then print:

# values greater than 5 AND less than 12
# values smaller than 3 OR greater than 13
# values NOT less than 10

arr = np.arange(1,15)
print(f"Array : \n{arr}")

print("\n")

print(f"Values greater than 5 and less than 12 : \n{arr[(arr>5) & (arr<12)]}")

print(f"Values smaller than 3 OR greater than 13 : \n{arr[(arr<3) | (arr>13)]}")

print(f"Values not less than 10 : \n{arr[~(arr<10)]}")



Array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Values greater than 5 and less than 12 : 
[ 6  7  8  9 10 11]
Values smaller than 3 OR greater than 13 : 
[ 1  2 14]
Values not less than 10 : 
[10 11 12 13 14]
